<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Authors.aspx.cs" Inherits="WebApplication2.WebForm3" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <p>
        <asp:Label ID="authorid" runat="server" Text="AuthorID"></asp:Label>
        </p>
        
        <p>
            <asp:Label ID="firstnamelabel" runat="server" Text="Име:   "></asp:Label>
            <asp:Textbox ID="firstname" runat="server"></asp:Textbox>
        </p>
        <p>
            <asp:Label ID="middlenamelabel" runat="server" Text="Презиме:   "></asp:Label>
            <asp:Textbox ID="middlename" runat="server"></asp:Textbox>
        </p>
        <p>
            <asp:Label ID="lastnamelabel" runat="server" Text="Фамилия:   "></asp:Label>
            <asp:Textbox ID="lastname" runat="server"></asp:Textbox>
        </p>
        <p>
            <asp:Label ID="paintingstylelabel" runat="server" Text="Стил на рисуване:   "></asp:Label>
            <asp:Textbox ID="paintingstyle" runat="server"></asp:Textbox>
        </p>
        <p>
            <asp:Label ID="yblabel" runat="server" Text="Дата на раждане:   "></asp:Label>
            <asp:Textbox ID="yb" runat="server" placeholder ="dd.MM.yyyy"></asp:Textbox>
        &nbsp;<asp:Button ID="Button2" runat="server" Text="Get Date" OnClick="Button2_Click" />
        </p>
        <p>
            <asp:Calendar ID="Calendar1" runat="server" OnSelectionChanged="Calendar1_SelectionChanged" Visible="False" BackColor="White" BorderColor="#3366CC" BorderWidth="1px" CellPadding="1" DayNameFormat="Shortest" Font-Names="Verdana" Font-Size="8pt" ForeColor="#003399" Height="200px" Width="220px">
                <DayHeaderStyle BackColor="#99CCCC" ForeColor="#336666" Height="1px" />
                <NextPrevStyle Font-Size="8pt" ForeColor="#CCCCFF" />
                <OtherMonthDayStyle ForeColor="#999999" />
                <SelectedDayStyle BackColor="#FF66FF" Font-Bold="True" ForeColor="#CCFF99" />
                <SelectorStyle BackColor="#99CCCC" ForeColor="#336666" />
                <TitleStyle BackColor="#003399" BorderColor="#3366CC" BorderWidth="1px" Font-Bold="True" Font-Size="10pt" ForeColor="#CCCCFF" Height="25px" />
                <TodayDayStyle ForeColor="White" />
                <WeekendDayStyle BackColor="#CCCCFF" />
            </asp:Calendar>
        </p>
        <td class="auto-style1" colspan="2">  
            <asp:Button ID="btnSaveUpdate" runat="server" Text="Save" Width="136px" OnClick="btnSaveUpdate_Click" />  
        </td> 

        <p>
            <asp:Label ID="Error" runat="server" Text="Label" Visible="False" ForeColor="Red" Font-Size="Larger" Font-Underline="true"></asp:Label>
        </p>

        <br />
        <div>
            <asp:GridView ID="Authors" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" BackColor="White" BorderColor="#336666" BorderStyle="Double" BorderWidth="3px" CellPadding="4" DataKeyNames="AuthorID" GridLines="Horizontal" OnRowDeleting="Authors_RowDeleting" OnSelectedIndexChanged="Authors_SelectedIndexChanged" AutoGenerateColumns="False">
                <FooterStyle BackColor="White" ForeColor="#333333" />
                <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="White" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F7F7F7" />
                <SortedAscendingHeaderStyle BackColor="#487575" />
                <SortedDescendingCellStyle BackColor="#E5E5E5" />
                <SortedDescendingHeaderStyle BackColor="#275353" />
                <Columns>
                    <asp:BoundField DataField="AuthorID" HeaderText="AuthorID"/>
                    <asp:BoundField DataField="FirstName" HeaderText="Име"/>
                    <asp:BoundField DataField="MiddleName" HeaderText="Презиме"/>
                    <asp:BoundField DataField="LastName" HeaderText="Фамилия"/>
                    <asp:BoundField DataField="PaintingStyle" HeaderText="Стил на рисуване"/>
                    <asp:BoundField DataField="YearBorn" HeaderText="Дата на раждане" DataFormatString="{0:dd.MM.yyyy}" />
                </Columns>
            </asp:GridView>
            <br />
            <br />
            <br />
            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Return to Home Page" />
        </div>
    </form>
</body>
</html>
