<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="WebApplication2.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
        <asp:DropDownList ID="authoridDD" runat="server" Width="202px" OnSelectedIndexChanged="authoridDD_SelectedIndexChanged" AutoPostBack="True">
        </asp:DropDownList>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
        <p>
        <asp:Label ID="authorid" runat="server" Text="AuthorID"></asp:Label>
            </p>
        <p>
        <asp:Label ID="paintingid" runat="server" Text="PaintingID"></asp:Label>
        </p>
        <p>
            <asp:Label ID="firstnamelabel" runat="server" Text="Име:   "></asp:Label>
            <asp:Label ID="firstname" runat="server"></asp:Label>
        </p>
        <p>
            <asp:Label ID="middlenamelabel" runat="server" Text="Презиме:   "></asp:Label>
            <asp:Label ID="middlename" runat="server"></asp:Label>
        </p>
        <p>
            <asp:Label ID="lastnamelabel" runat="server" Text="Фамилия:   "></asp:Label>
            <asp:Label ID="lastname" runat="server"></asp:Label>
        </p>
        <p>
            <asp:Label ID="paintingstylelabel" runat="server" Text="Стил на рисуване:   "></asp:Label>
            <asp:Label ID="paintingstyle" runat="server"></asp:Label>
        </p>
        <p>
            <asp:Label ID="yblabel" runat="server" Text="Дата на раждане:   "></asp:Label>
            <asp:Label ID="yb" runat="server" placeholder ="dd.MM.yyyy"></asp:Label>
        </p>
        <p>
            <asp:Label ID="paintingnamelabel" runat="server" Text="Име на картината:   "></asp:Label>
            <asp:TextBox ID="paintingname" runat="server"></asp:TextBox>
        </p>
        <p>
            <asp:Label ID="ymlabel" runat="server" Text="Дата на създаване на картината:   "></asp:Label>
            <asp:TextBox ID="ym" runat="server" placeholder ="dd.MM.yyyy"></asp:TextBox>
            &nbsp;<asp:Button ID="Button2" runat="server" Text="Get Date" OnClick="Button2_Click" />
        </p>
        <p>
            <asp:Calendar ID="Calendar1" runat="server" OnSelectionChanged="Calendar1_SelectionChanged" Visible="False" BackColor="White" BorderColor="#3366CC" BorderWidth="1px" CellPadding="1" DayNameFormat="Shortest" Font-Names="Verdana" Font-Size="8pt" ForeColor="#003399" Height="200px" Width="220px">
                <DayHeaderStyle BackColor="#99CCCC" ForeColor="#336666" Height="1px" />
                <NextPrevStyle Font-Size="8pt" ForeColor="#CCCCFF" />
                <OtherMonthDayStyle ForeColor="#999999" />
                <SelectedDayStyle BackColor="#FF66FF" Font-Bold="True" ForeColor="#CCFF99" />
                <SelectorStyle BackColor="#99CCCC" ForeColor="#336666" />
                <TitleStyle BackColor="#003399" BorderColor="#3366CC" BorderWidth="1px" Font-Bold="True" Font-Size="10pt" ForeColor="#CCCCFF" Height="25px" />
                <TodayDayStyle ForeColor="White" />
                <WeekendDayStyle BackColor="#CCCCFF" />
            </asp:Calendar>
        </p>
        <p>
            <asp:Label ID="mediumlabel" runat="server" Text="Използван материал:   "></asp:Label>
            <asp:TextBox ID="medium" runat="server"></asp:TextBox>
        </p>

        <td class="auto-style1" colspan="2">  
            <asp:Button ID="btnSaveUpdate" runat="server" Text="Save" Width="136px" OnClick="btnSaveUpdate_Click" />  
        </td> 

        <p>
            <asp:Label ID="Error" runat="server" Text="Label" Visible="False" ForeColor="Red" Font-Size="Larger" Font-Underline="true"></asp:Label>
        </p>

        <asp:GridView ID="GridView1" runat="server" BackColor="White" BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" CellPadding="3" CellSpacing="1" DataKeyNames="PaintingID" GridLines="None" OnRowDeleting="GridView1_RowDeleting" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AutoGenerateColumns="False">
            <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
            <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#594B9C" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#33276A" />
            <Columns>
                <asp:BoundField DataField="AuthorID" HeaderText="AuthorID"/>
                <asp:BoundField DataField="PaintingID" HeaderText="PaintingID"/>
                <asp:BoundField DataField="FirstName" HeaderText="Име"/>
                <asp:BoundField DataField="MiddleName" HeaderText="Презиме"/>
                <asp:BoundField DataField="LastName" HeaderText="Фамилия"/>
                <asp:BoundField DataField="PaintingStyle" HeaderText="Стил на рисуване"/>
                <asp:BoundField DataField="YearBorn" HeaderText="Дата на раждане" DataFormatString="{0:dd.MM.yyyy}" />
                <asp:BoundField DataField="NameOfPainting" HeaderText="Име на картината"/>
                <asp:BoundField DataField="MadeIn" HeaderText="Дата на създаване на картината" DataFormatString="{0:dd.MM.yyyy}"/>
                <asp:BoundField DataField="Medium" HeaderText="Използван материал"/>
           </Columns>
        </asp:GridView>

        
        <br />
        
        
        <br />
        <br />
        
        <br />
        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Return to Home Page" />
        
    </form>
</body>
</html>

